app/Http/routes.php
<?php

Route::group(['middleware' => 'auth'], function ()
{
    // Restricted routes go here
});

// Unrestricted routes go here
Route::get('/',['as' => 'dashboard', 'uses' => 'DashboardController@index']);
Route::get('/home',['as' => 'home', 'uses' => 'DashboardController@index']);

// USER INFO
Route::get('/messages', ['as' => 'my_messages', 'uses' => 'MessagesController@myMessages']);
Route::get('/profile', ['as' => 'profile', 'uses' => 'UsersController@profile']);
Route::get('/preferences', ['as' => 'preferences', 'uses' => 'UsersController@preferences']);

// COMPANIES
Route::get('/companies/newco', 'CompaniesController@newco');
Route::resource('companies', 'CompaniesController');

// PROJECTS
Route::resource('projects', 'ProjectsController');
Route::get('projects/{id}/gta', 'ProjectsController@contract_gta');
Route::post('project', ['as' => 'project_store', 'uses' => 'ProjectsController@store']);

// TEST ROUTES  Jon: 9012870209; Kenn: 8702083769; Tracy: 6624366086
Route::get('upload', function() {
    return View::make('pages.upload');
});
Route::post('apply/upload', 'ApplyController@upload');
Route::get('/emailer', function() {
    $data = array('name' => 'Jonathan'); // Change name

    Mail::send('emails.welcome', $data, function($message)
    {
        // Please double-check email address
        $message->to('jongravois@gmail.com')
            ->subject('Hi, there! Laravel sent me!');
    });

    return 'Email Sent!';
});
Route::get('/excel', ['as' => 'excel', 'uses' => 'ExcelController@index']);
Route::get('/event', function() {
    logit('created a test event');
});
Route::get('/tester', function () {
    return view('pages.tester');
});
Route::get('/notifier', function () {
    notify('2', '2', 'Angelina Jole just friended you.');
    return 'Notification Saved!';
});
Route::get('/sms/{phone}', function($phone) {
    Twilio::message($phone, 'Hi, I am Echo from the AeroEco software. I can now send but not receive text messages. Pretty cool, huh?');
    return 'Message sent';
});
Route::get('/messenger', function () {
    tweet('2', 'Dude, why are you sending yourself a message? Are you some kind of freak? Oh, you are just testing.');
    return 'Message Saved!';
});
Route::get('/welcome_page', function () {
    flash()->overlay('Hello, World!', 'This is the message');
    return view('pages.welcome');
});

// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register/{tier}', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// API
Route::group(['prefix' => 'api/'], function () {
    Route::resource('addresses', 'AddressesController');
    Route::resource('aircrafts', 'AircraftsController');
    Route::resource('atas', 'AtasController');
    Route::resource('companycontacts', 'CompanyContactsController');
    Route::resource('companies', 'CompaniesController');
    Route::resource('contracttypes', 'ContracttypesController');
    Route::resource('countries', 'CountriesController');
    Route::resource('disassemblers', 'DisassemblersController');
    Route::resource('locations', 'LocationsController');
    Route::resource('messages', 'MessagesController');
    Route::resource('notifications', 'NotificationsController');
    Route::resource('phones', 'PhonesController');
    Route::resource('projects', 'ProjectsController');
    Route::resource('projecttypes', 'ProjectTypesController');
    Route::resource('roles', 'RolesController');
    Route::resource('systemics', 'SystemicsController');
    Route::resource('users', 'UsersController');
});

app/User.php
<?php

namespace App;

use Carbon;
use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;

    protected $table = 'users';
    protected $fillable = ['firstname','lastname', 'email', 'password', 'company_id', 'all_companies', 'is_admin', 'can_sell', 'role_id', 'tier', 'location_id'];
    protected $hidden = ['password', 'remember_token'];

    /* CASTING */
    protected $casts = [
        'is_admin' => 'boolean',
        'can_sell' => 'boolean',
        'all_companies' => 'boolean'
    ];
    /* CASTING */

    /* Accessor & Mutators */
    public function getFullnameAttribute()
    {
        return $this->firstname . " " . $this->lastname;
    } // end getFullnameAttribute function
    /* Accessor & Mutators */

    /* RELATIONSHIPS */
    public function company()
    {
        return $this->belongsTo('App\Models\Company');
    }
    public function notifications()
    {
        return $this->hasMany('App\Models\Notification');
    }
    /* RELATIONSHIPS */

    /* METHODS */
    /* METHODS */
}

resources/views/layouts/partials/footer.blade.php
<div class="mainframe">
    <p class="copyright">&copy; {{date("Y")}} Aerospace Disassembly Consortium. All rights reserved.</p>
</div>

resources/views/layouts/partials/sidebar.blade.php
<div class="company__block">
    <h3 class="text-center">{{$company->company}}</h3>
    <p class="text-center">
        {!! HTML::image("vault/{$company->id}/logo.png", 'Logo', ['style' => 'width:120px; height: auto;']) !!}
    </p>
</div>
<ul class="sidebar-nav nav-pills nav-stacked" id="menu">
    {{--DASHBOARD--}}
    <li>
        <a href="/home"><span class="fa-stack fa-lg pull-left"><i class="fa fa-dashboard fa-stack-1x "></i></span> DASHBOARD</a>
    </li>

    @if( $user->can_sell || $user->id == 2)
        {{--ASSET OWNER--}}
        <li>
            <a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-plane fa-stack-1x"></i></span> ASSET OWNER</a>
            <ul class="nav-pills nav-stacked" style="list-style-type:none;">
                <li><a href="/projects/create"><span class="fa-stack fa-lg pull-left"><i class="fa fa-plus fa-stack-1x"></i></span>New Project</a></li>
                <li><a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-pencil fa-stack-1x"></i></span>Edit Project</a></li>
                <li><a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-folder fa-stack-1x"></i></span>Closed Projects</a></li>
                <li><a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-clock-o fa-stack-1x"></i></span>Modify Arrivals</a></li>
                <li><a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-bookmark fa-stack-1x"></i></span>GTA Contract</a></li>
            </ul>
        </li>
    @endif

    {{--BUYER--}}
    <li>
        <a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-truck fa-stack-1x "></i></span> BUYER</a>
        <ul class="nav-pills nav-stacked" style="list-style-type:none;">
            <li><a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-question-circle fa-stack-1x"></i></span>link1</a></li>
            <li><a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-question-circle fa-stack-1x"></i></span>link2</a></li>
        </ul>
    </li>

    @if( $user->is_admin || $user->id == 2)
        {{--ADMIN--}}
        <li>
            <a href="#"> <span class="fa-stack fa-lg pull-left"><i class="fa fa-lock fa-stack-1x "></i></span> ADMIN</a>
            <ul class="nav-pills nav-stacked" style="list-style-type:none;">
                <li><a href="#">link1</a></li>
                <li><a href="#">link2</a></li>
            </ul>
        </li>
    @endif

    @if( $user->company->id == 2 || $user->id == 2)
        {{--SALES--}}
        <li>
            <a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-bar-chart fa-stack-1x "></i></span> SALES</a>
            <ul class="nav-pills nav-stacked" style="list-style-type:none;">
                <li><a href="#">link1</a></li>
                <li><a href="#">link2</a></li>
            </ul>
        </li>
    @endif

    @if( $user->company->id == 2 || $user->id == 2)
        {{--TECH--}}
        <li>
            <a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-wrench fa-stack-1x "></i></span> TECH</a>
            <ul class="nav-pills nav-stacked" style="list-style-type:none;">
                <li><a href="#">link1</a></li>
                <li><a href="#">link2</a></li>
            </ul>
        </li>
    @endif

    @if( $user->role_id == 14 || $user->id == 2)
        {{--VENDOR--}}
        <li>
            <a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-bar-chart fa-stack-1x "></i></span> VENDOR</a>
            <ul class="nav-pills nav-stacked" style="list-style-type:none;">
                <li><a href="#">link1</a></li>
                <li><a href="#">link2</a></li>
            </ul>
        </li>
    @endif
</ul>

resources/views/layouts/partials/userbar.blade.php
<nav class="navbar navbar-default no-margin">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header fixed-brand">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" id="menu-toggle">
            <span class="fa fa-bars"></span>
        </button>
        <a class="navbar-brand" href="#">
            {!! HTML::image('images/inner_logo.png', 'Logo') !!}
        </a>
    </div><!-- navbar-header-->

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            {{--COLLAPSER--}}
            <li class="active" >
                <button class="navbar-toggle collapse in" data-toggle="collapse" id="menu-toggle-2">
                    &nbsp;<span class="fa fa-bars"></span>
                </button>
            </li>
            {{--NOTIFICATOR--}}
            <li class="dropdown hidden-xs">
                <notificator></notificator>
            </li>
            {{--MESSENGER--}}
            <li class="dropdown hidden-xs">
                <messenger></messenger>
            </li>
        </ul>
        {{--PROFILE BLOCK--}}
        <div class="nav-no-collapse pull-right" id="header-nav">
            <ul class="nav navbar-nav pull-right">
                <li class="dropdown profile-dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ Gravatar::src(Auth::user()->email) }}" alt="Gravatar"/>
                            <span class="hidden-xs">
                                {{ Auth::user()->fullname }}
                            </span> <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-right">
                        <li>
                            <a href="/profile">
                                <i class="fa fa-user">&nbsp;</i>&nbsp;Profile
                            </a>
                        </li>
                        <li>
                            <a href="/preferences">
                                <i class="fa fa-cog">&nbsp;</i>&nbsp;Settings
                            </a>
                        </li>
                        <li>
                            <a href="/messages"><i class="fa fa-envelope-o"></i>&nbsp;Messages</a>
                        </li>
                        <li>
                            <a href="/auth/logout"><i class="fa fa-power-off"></i>&nbsp;Logout</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div><!-- bs-example-navbar-collapse-1 -->
</nav>